import { writeFileSync, readdirSync, mkdirSync } from "fs";
import { join, basename } from "path";

const ROOT = new URL("..", import.meta.url).pathname;

// --- 画像マニフェスト生成（src/assets/images/ → src/generated/weaponImages.ts）---
const imagesDir = join(ROOT, "src/assets/images");
const imageFiles = readdirSync(imagesDir).filter((f) => f.endsWith(".png"));

const entries = imageFiles.map((f, i) => ({
  weaponName: basename(f, ".png"),
  file: f,
  idx: i,
}));

const imports = entries
  .map(({ file, idx }) => `import img${idx} from "../assets/images/${file}";`)
  .join("\n");

const mapEntries = entries
  .map(({ weaponName, idx }) => `  "${weaponName}": img${idx}.src,`)
  .join("\n");

const manifest = `// Auto-generated by scripts/prebuild.mts - DO NOT EDIT
${imports}

export const weaponImages: Record<string, string> = {
${mapEntries}
};

export function getWeaponImage(name: string): string | undefined {
  return weaponImages[name];
}
`;

mkdirSync(join(ROOT, "src/generated"), { recursive: true });
writeFileSync(join(ROOT, "src/generated/weaponImages.ts"), manifest);
console.log(`[prebuild] weaponImages.ts: ${entries.length} images`);
